---
- name: Install nginx
  ansible.builtin.package:
    name:
      - nginx
      - curl
    state: present
- name: Start and enable nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started
